DROP TABLE IF EXISTS Person CASCADE;
DROP TABLE IF EXISTS Gallery CASCADE;
DROP TABLE IF EXISTS Comment CASCADE;
DROP TABLE IF EXISTS Image CASCADE;
DROP TABLE IF EXISTS Vote CASCADE;
DROP TABLE IF EXISTS Tag CASCADE;
DROP TABLE IF EXISTS Gallery_Tag CASCADE;